# Generated by Django 5.0.2 on 2024-05-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='id categoria')),
                ('Nombre', models.TextField(max_length=40)),
                ('Descripcion', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pd_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Pedido')),
                ('Pd_Id_Usuario', models.BigIntegerField(verbose_name='ID del Usuario')),
                ('Pd_Fecha_envio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('prod_Nombre', models.CharField(max_length=255)),
                ('prod_Descripcion', models.TextField()),
                ('prod_Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_Talla', models.CharField(max_length=10)),
                ('prod_Color', models.CharField(max_length=50)),
                ('prod_Imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Usu_Documento', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='N° Documento')),
                ('Usu_Nombre', models.TextField(max_length=40)),
                ('Usu_Apellido', models.TextField(max_length=40)),
                ('Usu_Correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('Mp_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID  de pago')),
                ('Mp_Metodo', models.TextField(max_length=40)),
                ('Mp_Pago', models.IntegerField()),
                ('Mp_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.pedido', verbose_name='ID pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Producto',
            fields=[
                ('Env_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del envios')),
                ('Env_Fecha_hora', models.DateTimeField()),
                ('Env_Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.producto', verbose_name='ID del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('Detap_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle pedido')),
                ('Detap_Fecha_Envio', models.DateTimeField()),
                ('Detap_Direccion', models.TextField(max_length=40)),
                ('Detap_Estado_Envio', models.TextField(max_length=50)),
                ('Deta_Id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.pedido', verbose_name='ID Pedido')),
                ('Detap_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.usuario', verbose_name='ID Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('Ct_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Comentario')),
                ('Ct', models.TextField(max_length=250)),
                ('Ct_Cali', models.IntegerField()),
                ('Ct_Id_Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.producto', verbose_name='ID Producto')),
                ('Ct_Id_Usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.usuario', verbose_name='ID Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('Car_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID carro de compras')),
                ('Car_Estado', models.TextField(max_length=30)),
                ('Car_Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.producto', verbose_name='ID Producto')),
                ('Car_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoufitmen.usuario', verbose_name='ID Usuario')),
            ],
        ),
    ]
